### ISSUE TITLE
[Request] Disk Temp & Dataset Free Space

### ISSUE THREAD

**Issue by SeiyaGame** [Supporterino/truenas-graphite-to-prometheus#1]
Hi, thanks for your work! It's really insane
I was wondering if it was possible to add the temperature of the disks ? 
I tried on my side and without success, the names of the disks are weird:
![image](https://github.com/Supporterino/truenas-graphite-to-prometheus/assets/40237982/a3d390ad-7e20-4b69-8bd9-32d9ebe00ee5)
Also, if possible, I'd like to have the free space of my dataset/pool (To see the evolution of my storage space)

Thanks 👍

**Comment by mandrepont** [comment]
I had started working on the disk temp side. From what I can tell it is the disk serial number. Here is a mapping I think can be used.

```yaml

################################################
# Smart log mapping
################################################

- match: "truenas.*.smart_log_smart.disktemp.*.*"
  name: "disk_temp"
  labels:
    job: "truenas"
    instance: "${1}"
    disk_serial: "${2}"
```
