### ISSUE TITLE
Request: add prefix to metrics name

### ISSUE THREAD

**Issue by yuta1024** [Supporterino/truenas-graphite-to-prometheus#22]
Could you please add prefix to metrics name?
e.g.) `physical_memory` -> `truenas_physical_memory`

I think it will be easily to distinguish it from the metrics of other exporters. However, I am concerned that backwards compatibility will be broken...

**Comment by Supporterino** [comment]
I understand the request but I honestly don't like this approach since it would indeed break the backwards compatibility and I find it rather annoying to have such a prefix. You can work with the `job` label which is set by prometheus to narrow down your metrics if needed or if desperately want the prefix you can add it in your scrape_config like this:
```yaml
scrape_configs:
  - job_name: 'truenas_exporter'
    static_configs:
    - targets: ['localhost:9108']
       metric_relabel_configs:
         - source_labels: [__name__]
            target_label: __name__
            replacement: truenas_$1
```
