### ISSUE TITLE
The graphite_mapping.conf doesn't seem to be working for me.

### ISSUE THREAD

**Issue by silmarine** [Supporterino/truenas-graphite-to-prometheus#47]
I followed the guide and my grafana dashboard doesn't find any job or instance. I went to the prometheus page and looked for a couple of the metrics the dashboard was calling and couldn't find them but instead found much longer names that included the prefix and namespace set in Truenas. For example I find no "system_load" but instead " truenas_PXNAS1_system_load". Going off of the documentation of graphite_exporter I am guessing that it's not matching from the mappings and that is the default naming. My mapping config file is the same as the one here. I tried with the default and tried changing the job on each to "PXNAS1" but neither changed anything.  I've pasted some screenshots below, is this something I did wrong or a bug?

Truenas exporter settings:
![image](https://github.com/user-attachments/assets/d130a940-60fd-4a91-8e36-273525a85a7f)

Prometheus metric explorer search for "system_load" (there is both "scale_truenas" and "truenas_PXNAS1" because I was playing with the settings on Truenas trying to find the issue):
![image](https://github.com/user-attachments/assets/95bd87fc-4bd0-49ba-92dc-986eed66dcdc)

**Comment by Supporterino** [comment]
@silmarine seems like the configuration for the graphite_exporter isn't loaded correctly. Best guess would be to start the container with debug logging and analyzing the first few lines for errors

**Comment by cryptogeek13** [comment]
Just in case anyone stumbles into the exact same problem, like I did:

I had two different problems with my setup of `prom/graphite-exporter` using docker compose.

### First Problem
Docker Compose did not mount the `graphite_mapping.conf`, and created a folder instead.

**Solution:** use bind mounts (https://github.com/docker/compose/issues/9955)

### Second problem
I did not specify to load the `graphite_mapping.conf` when starting the container.

**Solution:** use `command` to load config from path where you mounted it into the container, e.g. like this `--graphite.mapping-config=/tmp/graphite_mapping.conf` (https://github.com/prometheus/graphite_exporter?tab=readme-ov-file#using-docker).

Here is my full docker-compose.yml, maybe it does help anyone:
```
services:
  graphite-exporter:
    image: prom/graphite-exporter:v0.16.0
    container_name: graphite-exporter
    user: '1000:1000'
    ports:
      - 9108:9108
      - 9109:9109
      - 9109:9109/udp
    volumes:
      - type: bind
        source: ./graphite-exporter/graphite_mapping.conf
        target: /tmp/graphite_mapping.conf
        bind:
          create_host_path: false
    command: '--graphite.mapping-config=/tmp/graphite_mapping.conf'
```
