### ISSUE TITLE
'instance' and 'job' are reserved labels

### ISSUE THREAD

**Issue by smoebody** [Supporterino/truenas-graphite-to-prometheus#78]
Hi, thanks for the effort to put these metrics into prometheus.

I found in my setup that the labels 'instance' and 'job', that you describe in the config-mapping are rewritten by prometheus to 'exported_instance' and 'exported_job'. Now i don't know whether this is specific to my setup, but i cannot think of any change that i have made here. Maybe something is missing from my prom-config. 

this is my prom-config:
```
- job_name: truenas
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
    - targets:
      - graphite-exporter:9108
```

This is what  a metric from prometheus looks like:
```
cpu_usage{cpu="cpu0", exported_instance="santa", exported_job="truenas", instance="graphite-exporter:9108", job="truenas", kind="guest"}
```
While 'job' is not that much of a problem since its identical (prometheus-job_name vs truenas_exporter-prefix) the instance changes indeed (prometheus-target vs truenas_exporter-namespace).

I don't know what is the best approach here. In my setup i replaced the variables and labels in the dashboard-json. That helped. I can provide a PR if you like.

cheers
Ulf
